# Generated by Django 4.0.5 on 2022-06-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=100)),
                ('prenom_auteur', models.CharField(max_length=100)),
                ('age_auteur', models.IntegerField()),
                ('photo_auteur', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100)),
                ('descriptif_categorie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('mail_joueur', models.EmailField(blank=True, max_length=254, null=True)),
                ('mdp_joueur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_joueur', models.CharField(blank=True, choices=[('PROFESSIONNEL', 'PRO'), ('PARTICULIER', 'PARTICULIER')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_jeux', models.CharField(max_length=100)),
                ('annee_jeux', models.IntegerField()),
                ('image_jeux', models.ImageField(blank=True, null=True, upload_to='images')),
                ('editeur_jeux', models.CharField(max_length=100)),
                ('auteur_jeux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_jeux', to='ludo.auteurs')),
                ('categorie_jeux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_jeux', to='ludo.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_commentaire', models.IntegerField()),
                ('commentaire_jeu', models.TextField(blank=True, null=True)),
                ('date_commentaire', models.DateField(blank=True, null=True)),
                ('jeux_commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.jeux')),
                ('joueur_commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.joueurs')),
            ],
        ),
    ]
