# Generated by Django 4.0.5 on 2022-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='photo_auteur',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='image_jeux',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
